INSERT INTO BASE_USER VALUES (BASE_USER_SEQUENCE.NEXTVAL, 'member', '1234', 'ROLE_MEMBER');
INSERT INTO MEMBER VALUES (1, 'member', 'parkshark', 'central street 42', '1000', 'Brussels', 'Belgium', 'member.parkshark@local.be', '0123456789', '1ABC123', 'Belgium', TO_DATE('2019/09/02 09:00:00', 'yyyy/mm/dd hh24:mi:ss'));

INSERT INTO BASE_USER VALUES (BASE_USER_SEQUENCE.NEXTVAL, 'manager', '1234', 'ROLE_MANAGER');
INSERT INTO MANAGER VALUES (2, 'manager', 'parkshark');

INSERT INTO PARKING_LOT_CONTACT_PERSON(ID, NAME, E_MAIL, PHONE_NUMBER, TELEPHONE_NUMBER, STREET_NAME, STREET_NUMBER, POST_CODE, POST_LABEL)
VALUES ('1', 'Kevin', 'kevin@hotmail.com', '0474559632', NULL, 'Street One', '25', '1000', 'Brussels');
INSERT INTO PARKING_LOT_CONTACT_PERSON(ID, NAME, E_MAIL, PHONE_NUMBER, TELEPHONE_NUMBER, STREET_NAME, STREET_NUMBER, POST_CODE, POST_LABEL)
VALUES ('2', 'David', 'david@hotmail.com', '0851525589', NULL, 'Street Two', '99', '3000', 'Leuven');