CREATE TABLE DIVISION
(
    ID                  NUMBER,
    NAME                VARCHAR2(50) UNIQUE NOT NULL,
    ORIGINAL_NAME       VARCHAR2(50)        NOT NULL,
    DIRECTOR_FIRST_NAME VARCHAR2(50)        NOT NULL,
    DIRECTOR_LAST_NAME  VARCHAR2(50)        NOT NULL,
    CONSTRAINT PK_DIVISION PRIMARY KEY (ID)
);

CREATE SEQUENCE DIVISION_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE BASE_USER
(
    ID NUMBER,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_BASE_USER PRIMARY KEY (ID)
);
CREATE SEQUENCE BASE_USER_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE MEMBER
(
    ID                  NUMBER,
    FIRST_NAME          VARCHAR2(50)        NOT NULL,
    LAST_NAME           VARCHAR2(50)        NOT NULL,
    STREET_AND_NUMBER   VARCHAR2(50)        NOT NULL,
    ZIP_CODE            VARCHAR2(15)        NOT NULL,
    CITY                VARCHAR2(50)        NOT NULL,
    COUNTRY             VARCHAR2(50)        NOT NULL,
    EMAIL               VARCHAR2(50)        NOT NULL,
    PHONE               VARCHAR2(15)        NOT NULL,
    LICENCE_PLATE_NUMBER    VARCHAR2(15)    NOT NULL,
    LICENCE_PLATE_COUNTRY   VARCHAR2(50)    NOT NULL,
    REGISTRATION_DATE   DATE                NOT NULL,
    CONSTRAINT  PK_MEMBER PRIMARY KEY (ID),
    CONSTRAINT FK_MEMBER_BU FOREIGN KEY (ID) references BASE_USER(ID)
);
-- CREATE  SEQUENCE MEMBER_SEQUENCE START WITH 1 INCREMENT BY 1;


