CREATE TABLE DIVISION
(
    ID                  NUMBER,
    NAME                VARCHAR2(50) UNIQUE NOT NULL,
    ORIGINAL_NAME       VARCHAR2(50)        NOT NULL,
    DIRECTOR_FIRST_NAME VARCHAR2(50)        NOT NULL,
    DIRECTOR_LAST_NAME  VARCHAR2(50)        NOT NULL,
    CONSTRAINT PK_DIVISION PRIMARY KEY (ID)
);

CREATE SEQUENCE DIVISION_SEQUENCE START WITH 1 INCREMENT BY 1;